### ISSUE TITLE
No colors in popup

### ISSUE THREAD

**Issue by cstuder** [mchugh19/zabbix-vue#24]
Starting today, Zabbix Vue doesn't show any colors in the popup:

![image](https://user-images.githubusercontent.com/288493/55309058-e2c81a80-545c-11e9-8eaa-623c51bf57e0.png)

Using Chrome 73 with Zabbix Vue 1.0.12.

I can't see anything in the commit log which might have triggered this.

(The Firefox Addons store is still offering Zabbix Vue 1.0.11 which still has colors.)

**Comment by Tigerteron** [comment]
Hi
I have same problem, I reinstalled extension on chrome but problem not resolved

**Comment by flunda** [comment]
Hi,

same here. Since today. Also the default extension's icon is black instead of the color of the highest warning, Chrome version Version 73.0.3683.86. Vue Version 1.0.12_0. Also tried reinstalling it and clearing data, but the issue still extists. Looks like there is some kind of incompatibility with the newes Chrome Version.

**Comment by mchugh19** [comment]
Gah! Sorry all, I'll have to investigate this. 
The 1.0.12 release was forced by Google as Zabbix Vue had been pulled from the chrome store for an unspecified reason. It wasn't a fun process, but I managed to finally get someone to tell me what the issue was (they wanted a more detailed description).

So the only change the 1.0.12 should have included is updating that single line in the manifest, but I ended up having to setup and run the build on my windows laptop. I'm guessing it is very possible that something was very not happy about that environment or build process, so I'll take a look at rebuilding.

**Comment by aceslup** [comment]
same problem. Thank you for your shareing

**Comment by mchugh19** [comment]
Hey all. Just pushed 1.0.13 to the chrome store. I've verified that it includes the proper colors and png support. Sorry for the bother.

**Comment by flunda** [comment]
Hey, thanks for pushing 1.0.13 - that indeed fiexed the issue regarding the colors and stylings. But now i've found out that the pop-up messages are not working, also the icon does not get updated automatically when an error is gone, or a new one arises. It stays always the same, only if i update the extenstion's config, it is updating.

**Comment by mchugh19** [comment]
@flunda I've been unable to replicate that issue. After restarting the browser do you still see that activity?

**Comment by flunda** [comment]
@mchugh19 Hi! Sorry for the belated reply, currently it seems we have an issue again. Since i have upgraded to the latest version of Google Chrome (Version 80.0.3987.87 - 64 bit) the Icon stays orange also when there are no issues in Zabbix (before the Icon was also green when no issues present in Zabbix).

Can you please check?

thanks a lot
flunda

**Comment by mchugh19** [comment]
@flunda 
I've only seen these types of issues when the extension is freshly installed. Once chrome or Firefox are restarted, everything seems to work ok. Are you still seeing this behavior after a browser restart?

**Comment by Tigerteron** [comment]
I reinstall chrome and extension but nothing changed:
1-zabbix 4.4.4
2-Chrome 80
3-zabbix vue 1.14
![Annotation 2020-02-12 065749](https://user-images.githubusercontent.com/49148135/74300500-2837c280-4d65-11ea-80ed-a4334fce6a82.jpg)

**Comment by flunda** [comment]
@mchugh19 Still seeing this behavior also after a restart of the browser and reboot of the PC. 
What is also strange, it stays black for about 4-5 seconds then it is turning to orange (but as you can see no issues currently present)
![image](https://user-images.githubusercontent.com/19301394/74317736-38a76780-4d7c-11ea-86c5-d4ce9a1bddc2.png)

**Comment by flunda** [comment]
@mchugh19 Update: i have removed the extension and added it back agin and now the icon stays black at all, but displaying all the issues, just not changing the color. Looks like the original issue.

![image](https://user-images.githubusercontent.com/19301394/74639497-4e4ad180-516e-11ea-9cdd-2c1ffe6cb57d.png)

**Comment by mchugh19** [comment]
I'll keep playing around with this. So far I am unable to replicate.

**Comment by Tigerteron** [comment]
Dear Christian;
one of my friends is developer is how extension to him and he fix by following changes:
1-convert all svg to png
2-change images in background.js
for example:
sev_-1.svg convert to sev_-1.png
and change sev_-1.svg to sev_-1.png in background.js
i tested two days an all things worked fine
i hope this help to you

**Comment by mchugh19** [comment]
Sounds like png images have better compatibility than svg. Just pushed a change to use png, and released this as 1.15. Please let me know if you continue to have problems.

**Comment by flunda** [comment]
@mchugh19 Thank you for fixing this. Could you please be so kind and push it also to Google Chome store so our Clients can install it directly from there?

thanks a lot

**Comment by mchugh19** [comment]
@flunda yep, it's in the Google approval queue. Hopefully released soon!
