### ISSUE TITLE
Update 10.04.2021

### ISSUE THREAD

**Issue by kreizz** [mchugh19/zabbix-vue#33]
After the update on 10.04.2021 it got really bad. Out of 100 events in zabbix, the plugin displays only 10 and in very large print. In addition, the connection with zabbix constantly disappears

Is it possible to revert to a previous version?

**Comment by mchugh19** [comment]
I'll look into this. 

The new build was done to work around issues with deprecated javascript build tooling. But you can checkout the previous commits, and build it should still work. 

Bad displays of more than 10 items sounds like a problem with vuetify's table display. So I think I've got a good idea of where to look. 

Thanks for the report

**Comment by mchugh19** [comment]
Looks like vuetify 2 changed the way pagination was handled, so that only 10 items were displayed. I've just fixed that in the attached build. Are you able to test to see if this helps?  [Archive.zip](https://github.com/mchugh19/zabbix-vue/files/6292486/Archive.zip)

The font size to me is not changed. Do you get something different than this? 
<img width="817" alt="Screenshot 2021-04-11 at 19 22 01" src="https://user-images.githubusercontent.com/1360357/114316410-58125f80-9afb-11eb-9511-1925eaf7e230.png">

Regarding connectivity, what are you experiencing?

**Comment by mchugh19** [comment]
I think I may have resolved your issues. 

The 2.0 release corrected an error with the zabbix logout function. But if there was an issue in logout, it could cause issues. Now logout will still be run, but won't cause the plugin to report errors. 

I've also added some css to make the table display slightly more dense. 
<img width="817" alt="Screenshot 2021-04-11 at 20 34 10" src="https://user-images.githubusercontent.com/1360357/114318532-5057b880-9b05-11eb-8607-65dbffef2be7.png">

I've just released this on the chrome and firefox stores, and it should be available shortly for testing.

**Comment by kreizz** [comment]
seems its ok now. thanks =)

**Comment by mchugh19** [comment]
Glad to hear it. Closing this out, but please let me know if there's anything else broken or needing work.

**Comment by kreizz** [comment]
Unfortunately, I must return to this question, because most of these buttons do not work. 
![26-04-2021 18-23-28](https://user-images.githubusercontent.com/82328036/116109192-3d281980-a6bd-11eb-8f0d-84c1d4d85d36.jpg)

**Comment by brlumen** [comment]
@kreizz , I faced this problem too. Reinstalling the plugin helped me.

**Comment by mchugh19** [comment]
@kreizz unfortunately I am not able to replicate your issue. 
With the latest update, the plugin now detects the version of Zabbix used. This was needed as the URLs for the buttons are different across versions. Since this version detection is done on the options screen, you could try reconfiguring your server settings (simply modifying a character in the url field should be enough to trigger the version detection). As long as you see the zabbix version number under the url field, you can save settings, and everything should operate as expected. 

Are you still seeing issues?
