### ISSUE TITLE
SAML authentication

### ISSUE THREAD

**Issue by nixadmin** [mchugh19/zabbix-vue#59]
This beautiful application has no other authentication than the standard one. This is not entirely safe for users and many are already starting to use SSO. What matters to me is the way to authenticate using SAML. Is it possible to add such a feature in the future?

**Comment by mchugh19** [comment]
Just added support for Zabbix token auth (will be released as 2.1.0). This isn't much different from the standard username/password, but it allows querying for zabbix alerts with a single call rather than needing 3 (login, triggers, logout). As these are the only login methods offered by the Zabbix API, there isn't a direct SAML ability.
